### ISSUE TITLE
wrong size for the recovered integer array

### ISSUE THREAD

**Issue by mokun** [lemire/JavaFastPFOR#44] opened 2019-11-08 22:20 UTC
I believe There is mistake in setting the size of the recovered int[] to `ChunkSize` in the advancedExample() method in https://github.com/lemire/JavaFastPFOR/blob/master/example.java, 

```
int TotalSize = 2342351; // some arbitrary number
int ChunkSize = 16384; // size of each chunk, choose a multiple of 128

int[] data = new int[TotalSize];

int[] recovered = new int[ChunkSize];

```

If I do the following at the end: 
```
        if(Arrays.equals(data, recovered)) {
            System.out.println("Elevation data is recovered in memory without loss");
        }
        else
            throw new RuntimeException("bug"); // could use assert
```

It would throw me the RuntimeException, since the data array and the recovered array are different and NOT of the same size.

https://github.com/lemire/JavaFastPFOR/blob/1d650e40f6ce3052042871161488971052c9fd32/example.java#L240-L243

**Comment by mokun** [comment] 2019-11-08 22:21
> I believe There is mistake in setting the size of the recovered int[] to ChunkSize in the advancedExample() method in https://github.com/lemire/JavaFastPFOR/blob/master/example.java,
> 
> `int[] recovered = new int[ChunkSize];`
> 
> ```
> int TotalSize = 2342351; // some arbitrary number
> int ChunkSize = 16384; // size of each chunk, choose a multiple of 128
> 
> int[] data = new int[TotalSize];
> ```
> 
> If I do the following at the end:
> 
> ```
>         if(Arrays.equals(data, recovered)) {
>             System.out.println("Elevation data is recovered in memory without loss");
>         }
>         else
>             throw new RuntimeException("bug"); // could use assert
> ```
> 
> It would throw me the RuntimeException, since data and recovered are not of the same size.
> 
> https://github.com/lemire/JavaFastPFOR/blob/1d650e40f6ce3052042871161488971052c9fd32/example.java#L240-L243

**Comment by lemire** [comment] 2019-11-09 01:16
Please provide a complete and reproducible code sample.

If you think that the example exactly as written is wrong, say so. If it is some other example that you have written that is not working as you expect, please provide the full example.

Please provide all necessary details for reproduction.

**Comment by blacelle** [comment] 2022-11-25 12:42
The provided snippet looks weird, as we compare the initial data (size=2342351) with a chunk of the restored data (size= 16384).

**Comment by blacelle** [comment] 2022-11-25 17:11
@lemire example.java is the project looks perfectly fine :

https://github.com/lemire/JavaFastPFOR/blob/1d650e40f6ce3052042871161488971052c9fd32/example.java#L252-L254

But the code from @mokun looks weird, as it calls `Arrays.equals` over arrays of different length.

**Comment by lemire** [comment] 2022-11-25 19:14
I think that I am going to close this issue. I am always happy to receive criticism and questions, but I need to understand it to be able to process it. In this instance, I do not understand what the issue is.

**Closed by lemire** 2022-11-25 19:14 UTC
